7 - Python Set Path in Windows and Help

In [3]:
print("Hello, World!")

Hello, World!


In [7]:
help()


Welcome to Python 3.12's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the internet at https://docs.python.org/3.12/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".


Here is a list of available topics.  Enter any topic name to get more help.

ASSERTION           DELETION            LOOPING             SHIFTING
ASSIGNMENT          DICTIONARIES        MAPPINGMETHODS      SLICINGS
ATTRIBUTEMETHODS    DICTIONARYLITERALS  MAPPINGS            SPECIALATTRIBUTES
ATTRIBUTES          DYNAMICFEATURES     MET

10 - Data Types in Python

In [8]:
num = 2.5
type(num)

float

In [9]:
num = 5
type(num)

int

In [10]:
num = 6+9j
type(num)

complex

In [19]:
a = 5.6
b = int(a)
print(b, type(b))

5 <class 'int'>


In [21]:
k = float(b)
print(k, type(k))

5.0 <class 'float'>


In [22]:
k = 6
c = complex(b, k)
c

(5+6j)

In [23]:
b < k

True

In [25]:
bool = b < k
print(bool, type(bool))

True <class 'bool'>


In [26]:
b > k

False

In [27]:
int(True)

1

In [29]:
int(False)

0

In [30]:
lst = [1, 2, 3, 4, 5]
type(lst)

list

In [31]:
s = {1, 2, 3, 4, 5}
type(s)

set

In [32]:
t = (1, 2, 3, 4, 5)
type(t)

tuple

In [34]:
str = "Hello, World!"
st = 'Mukul'

print(st, type(st))
print(str, type(str))

Mukul <class 'str'>
Hello, World! <class 'str'>


In [35]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

<class 'type'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
list(range (2,10,2))

[2, 4, 6, 8]

In [1]:
type(range(10))

range

In [6]:
d = {'name': 'mukul', 'os' : 'arch-linux' , 'ide' : 'vs-code', 'city': 'ayodhya'}
d

{'name': 'mukul', 'os': 'arch-linux', 'ide': 'vs-code', 'city': 'ayodhya'}

In [7]:
d.keys()

dict_keys(['name', 'os', 'ide', 'city'])

In [8]:
d.values()

dict_values(['mukul', 'arch-linux', 'vs-code', 'ayodhya'])

In [9]:
d['name']

'mukul'

In [10]:
d.get('os')

'arch-linux'

17 - Swap Two Values

The classic way to swap the values of two variables using a temporary variable.

In [ ]:
a = 5
b = 3
print (a,b)

temp = a
a = b
b = temp

print (a,b)

5 3
3 5


Swap the values of two variables (a and b) without using a temporary variable.

In [ ]:
a = 3
b = 9
print (a,b)

a = a+b
b = a-b
a = a-b

print (a,b)

3 9
9 3


Swap the values of two variables, a and b, using the XOR bitwise operator (^).

In [ ]:
a = 7
b = 5
print (a,b)

a = a ^ b
b = a ^ b
a = a ^ b

print (a,b)

7 5
5 7


18 - User input in Python

In [ ]:
name = input ("Enter Your Name: ")
print(name)

Enter Your Name: Mukul
Mukul


In [ ]:
x = input ("Enter First Number: ")
y = input ("Enter Second Number: ")
z = x+y
print(z)

Enter First Number: 4
Enter Second Number: 5
45


In [ ]:
x = int (input ("Enter First Number: "))
y = int (input ("Enter Second Number: "))
z = x+y
print(z)

Enter First Number: 4
Enter Second Number: 5
9


This code snippet gets input from the user and then prints only the first character of that input.

In [ ]:
ch = input ('Enter a character: ') [0]
print (ch)

Enter a character: asdad
a


This code snippet gets input from the user, treats that input as a Python expression, evaluates it, and then prints the result.

In [ ]:
result = eval (input ('Enter an Expression: '))
print (result)

Enter an Expression: 5+5-3
7


In [ ]:
import sys

x = int(sys.argv[1])
y = int(sys.argv[2])

z=x+y

print (z)

26 - Array

In [ ]:
from array import *

vals = array('i',[4,3,5,6,])
print(vals)

array('i', [4, 3, 5, 6])


In [ ]:
from array import *

vals = array('i',[1,3,4.5,5.0])
print(vals)

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
from array import *

vals = array('i',[1,2,3,-4,5])
print(vals)

array('i', [1, 3, -4, 5, 6])


In [ ]:
from array import *

vals = array('I',[1,2,3,-4,5])
print(vals)

OverflowError: can't convert negative value to unsigned int

In [ ]:
from array import *

vals = array('i',[1,2,3,4,5])
vals.reverse()

print(vals)

array('i', [5, 4, 3, 2, 1])


In [ ]:
from array import *

vals = array('i',[1,2,3,4,5])
print(vals[2])

3


In [ ]:
from array import *

vals = array('i',[1,2,3,4,5])

for i in range(5):
  print(vals[i])

1
2
3
4
5


In [ ]:
from array import *

vals = array('i',[1,2,3,4,5])

for i in range(len(vals)):
  print(vals[i])

1
2
3
4
5


In [ ]:
from array import *

vals = array('i',[1,2,3,4,5])

for e in vals:
  print(e)

1
2
3
4
5


In [ ]:
from array import *

vals = array('u',['a','e','i','o','u'])
print(vals)

for e in vals:
  print(e)

array('u', 'aeiou')
a
e
i
o
u


In [ ]:
from array import *

vals = array('i',[1,2,3,4,5])

newArr = array(vals.typecode, (a*a for a in vals))

# for e in newArr:
#   print(e)

i = 0

while i<len(newArr):
  print(newArr[i])
  i += 1

1
4
9
16
25


In [ ]:
from array import *

arr = array('i',[])

l = int(input("Enter the length of the array: "))

for i in range(l):
  x = int(input("Enter the next value: "))
  arr.append(x)

print(arr)

Enter the length of the array: 3
Enter the next value: 2
Enter the next value: 4
Enter the next value: 6
array('i', [2, 4, 6])


In [ ]:
from array import *

arr = array('i',[])

l = int(input("Enter the length of the array: "))

for i in range(l):
  x = int(input("Enter the next value: "))
  arr.append(x)

print(arr)

val = int(input("Enter the value for search: "))
k = 0
for e in arr:
  if e==val:
    print(k)
    break
  k+=1

print(arr.index(val))

Enter the length of the array: 5
Enter the next value: 8
Enter the next value: 4
Enter the next value: 5
Enter the next value: 2
Enter the next value: 6
array('i', [8, 4, 5, 2, 6])
Enter the value for search: 5
2
2


28 - Numpy

In [1]:
!pip install numpy

  Using cached numpy-2.3.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.1-cp312-cp312-win_amd64.whl (12.7 MB)


In [ ]:
from numpy import *

arr = array([1,2,3,6,5,4],int)
print(arr)

[1 2 3 6 5 4]


In [ ]:
from numpy import *

arr = array([

             [1,2,3],
             [6,5,4]
])

print(arr)

print(arr.dtype)

print(arr.ndim)

print(arr.shape)

print(arr.size)

[[1 2 3]
 [6 5 4]]
int64
2
(2, 3)
6


In [ ]:
from numpy import *

arr = array([

             [1,2,3],
             [6,5,4]
])

arr2 = arr.flatten()
print(arr2)

[1 2 3 6 5 4]


In [ ]:
from numpy import *

arr = array([

             [1,2,3,4,5,6],
             [3,5,0,7,8,9]
])

arr3 = arr.reshape(3,4)
print(arr3)

[[1 2 3 4]
 [5 6 3 5]
 [0 7 8 9]]


In [ ]:
from numpy import *

arr = array([

             [1,2,3,7,8,9],
             [4,5,6,1,2,3]
])

arr2 = arr.reshape(2,2,3)
print(arr2)

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [1 2 3]]]


In [ ]:
from numpy import *

arr = array([

             [1,2,3,4],
             [5,6,7,8]
])

m = matrix(arr)

print(m)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
from numpy import *

# m = matrix('1 2 3 ; 4 5 6')

# m = matrix('1 2; 3 4; 5 6')

m = matrix('1 2 3; 4 5 6; 7 8 9')

# print(m)
print(m.diagonal())

[[1 5 9]]


In [ ]:
from numpy import *

m1 = matrix('1 2 3; 4 5 6; 7 8 9')
m2 = matrix('1 2 3; 4 5 6; 7 8 9')

m3 = m1 * m2

print(m3)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
from numpy import *

m1 = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]

m2 = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]

result_matrix = [[0, 0, 0],
                 [0, 0, 0],
                 [0, 0, 0]]


for i in range(len(m1)):
  for j in range(len(m2[0])):
   for k in range(len(m2)):
      result_matrix[i][j] += m1[i][k] * m2[k][j]

print("Result of 3x3 matrix multiplication:")
for row in result_matrix:
  print(row)

Result of 3x3 matrix multiplication:
[30, 36, 42]
[66, 81, 96]
[102, 126, 150]


32 - Functions in Python

In [ ]:
def greet():
  print("Hello")
  print("Good Morning")

def add(x,y):
  c = x + y
  print(c)

# greet()

add(2,3)


5


In [ ]:
def add_sub(x,y):
  a = x + y
  s = x - y
  return a,s

result1, result2 = add_sub(5,3)
print(result1)
print(result2)

8
2


34 - Function Arguments in Python

In [ ]:
def update(x):
  x = 8
  print("x ",x)

a = 10
update(a)
print("a ",a)

x  8
a  10


In [ ]:
def update(x):

  print(id(x))
  x = 8
  print(id(x))
  print("x ",x)

a = 10
print(id(a))
update(a)
print("a ",a)

10758024
10758024
10757960
x  8
a  10


In [ ]:
def update(x):

  print(id(x))
  x[1] = 25
  print(id(x))
  print("x ",x)

a = [10,20,30]
print(id(a))
update(a)
print("a ",a)

133945508199168
133945508199168
133945508199168
x  [10, 25, 30]
a  [10, 25, 30]


34 - Types of Arguments in Python

In [ ]:
def add(a, b):
    c = a + b
    print(c)

add(5, 6)

11


In [ ]:
def person(name, age):
  print(name)
  print(age)

person('mukul',25)

mukul
25


In [ ]:
def person(name, age=26):
  print(name)
  print(age)

person(age=25, name='mukul')

mukul
25


In [ ]:
# def sum(a, *b):
def sum(*b):

  c = 0

  # c = a

  for i in b:
    c = c + i

  print(c)

sum(5,6,2,9)

22


35 - Keyworded Variable Length Arguments in Python

In [ ]:
def person(name,*data):

    print(name)
    print(data)

person('mukul', 25, 'Ayodhya', 76975)

mukul
(28, 'Ayodhya', 76975)


In [ ]:
def person(name,**data):

    print(name)
    print(data)

person('mukul', age=25, city='Ayodhya', mob=76975)

mukul
{'age': 25, 'city': 'Ayodhya', 'mob': 76975}


In [ ]:
def person(name,**data):

    print(name)
    for i,j in data.items():
      print(i,j)

person('mukul', age=25, city='Ayodhya', mob=76975)

mukul
age 25
city Ayodhya
mob 76975


36 - Global Keyword in Python | Global vs Local Variable

In [ ]:
a  = 10

def something():
  a = 15

  print("in fun ",a)

something()

print("Outside ",a)



in fun  15
Outside  10


In [ ]:
a = 10

def something():
  a = 15
  print("Inside ",a)

something()
print("Outside ",a)


print(a)

Inside  15
Outside  10
10


In [ ]:
a  = 10

def something():
  global a
  a = 15

  print("in fun ",a)

something()

print("Outside ",a)


in fun  15
Outside  15


In [ ]:
a  = 10
print(id(a))

def something():

  a = 9

  x = globals()['a']

  print(id(x))

  print("in fun ",a)

something()

print("Outside ",a)



10758024
10758024
in fun  9
Outside  10


In [ ]:
a  = 10
print(id(a))

def something():

  a = 9

  x = globals()['a']

  print(id(x))

  print("in fun ",a)

  globals()['a'] = 15

something()

print("Outside ",a)



10758024
10758024
in fun  9
Outside  15


37 - Pass List to a Function in Python

In [ ]:

def count(lst):
  even = 0
  odd = 0
  for i in lst:
    if i%2==0:
      even+=1
    else:
      odd+=1
  return even, odd

lst = {1,2,3,4,5,6,7,8,9}

even, odd = count(lst)

print("Even: {} and Odd: {}".format(even, odd))

Even: 4 and Odd: 5


Count Odd and Even Numbers from a User Input List

In [ ]:
def count(lst):
    even = 0
    odd = 0
    for i in lst:
        if i % 2 == 0:
            even += 1
        else:
            odd += 1
    return even, odd

nums = input("Enter numbers (space-separated): ")

nums = nums.split()
nums = [int(n) for n in nums]

even, odd = count(nums)

print("Even: {} and Odd: {}".format(even, odd))


Enter numbers (space-separated): 11 23 45 67 89 98
Even: 1 and Odd: 5


Assignment - Take 10 Names from user and count and display the number of users name has more than 5 letters

In [ ]:
names = []

for i in range(10):
    name = input(f"Enter name {i+1}: ")
    names.append(name)

count = 0
for n in names:
    if len(n) > 5:
        count += 1

print("Number of names with more than 5 letters:", count)

Enter name 1: Mukul
Enter name 2: Shubham
Enter name 3: Saurabh
Enter name 4: Akshat
Enter name 5: Shivam
Enter name 6: Rishi
Enter name 7: Rishabh
Enter name 8: Harshit
Enter name 9: Tushar
Enter name 10: Ram
Number of names with more than 5 letters: 7


In [ ]:
def count_names_longer_than_five():
  long_names_count = 0
  for i in range(10):
    name = input(f"Enter name {i + 1}: ")
    if len(name) > 5:
      long_names_count += 1
  print(f"Number of names with more than 5 letters: {long_names_count}")

count_names_longer_than_five()


Enter name 1: Shubham
Enter name 2: Shivam
Enter name 3: Mukul
Enter name 4: Praveen
Enter name 5: Telusko
Enter name 6: Rishabh
Enter name 7: Harshit
Enter name 8: Shyam
Enter name 9: Saurabh
Enter name 10: Prajjwal
Number of names with more than 5 letters: 8


38 - Fibonacci Sequence

In [ ]:
def fib(n):

  a = 0
  b = 1

  if n==1:
    print(a)
  else:
    print(a)
    print(b)

    for i in range(2,n):
      c = a + b
      a = b
      b = c
      print(c)

fib(10)

0
1
1
2
3
5
8
13
21
34


Assignment: 1 - Fibonacci Series with Check for Negative Input

In [ ]:
def fib(num):
  a = 0
  b = 1

  if num <= 0:
    print("Please enter a positive integer.")
  elif num == 1:
    print(a)
  else:
    print(a)
    print(b)

    for i in range(2, num):
      c = a + b
      a = b
      b = c
      print(c)

num = input("Enter a number: ")
try:
    num = int(num)
    fib(num)
except ValueError:
    print("Invalid input. Please enter an integer.")

Enter a number: 6
0
1
1
2
3
5


Assignment: 2 - Print Fibonacci numbers that are less than the number entered by the user

In [ ]:
def fib(num):
    if num <= 0:
        print("Please enter a positive number.")
        return

    a = 0
    b = 1

    while a < num:
        print(a)
        c = a + b
        a = b
        b = c

num = input("Enter a number: ")
try:
    num = int(num)
    fib(num)
except ValueError:
    print("Invalid input. Please enter an integer.")


Enter a number: 100
0
1
1
2
3
5
8
13
21
34
55
89


39 - Factorial

In [ ]:
def fact(n):

  f = 1

  for i in range(1,n+1):
    f = f*i

  return f

x = 4

result = fact(x)

print(result)

24


40 - Recurrsion

In [ ]:
import sys

sys.setrecursionlimit(2000)

print(sys.getrecursionlimit())

i = 0

def greet():
  global i
  i+=1
  print("Hello", i)
  greet()

greet()

2000
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
Hello 7
Hello 8
Hello 9
Hello 10
Hello 11
Hello 12
Hello 13
Hello 14
Hello 15
Hello 16
Hello 17
Hello 18
Hello 19
Hello 20
Hello 21
Hello 22
Hello 23
Hello 24
Hello 25
Hello 26
Hello 27
Hello 28
Hello 29
Hello 30
Hello 31
Hello 32
Hello 33
Hello 34
Hello 35
Hello 36
Hello 37
Hello 38
Hello 39
Hello 40
Hello 41
Hello 42
Hello 43
Hello 44
Hello 45
Hello 46
Hello 47
Hello 48
Hello 49
Hello 50
Hello 51
Hello 52
Hello 53
Hello 54
Hello 55
Hello 56
Hello 57
Hello 58
Hello 59
Hello 60
Hello 61
Hello 62
Hello 63
Hello 64
Hello 65
Hello 66
Hello 67
Hello 68
Hello 69
Hello 70
Hello 71
Hello 72
Hello 73
Hello 74
Hello 75
Hello 76
Hello 77
Hello 78
Hello 79
Hello 80
Hello 81
Hello 82
Hello 83
Hello 84
Hello 85
Hello 86
Hello 87
Hello 88
Hello 89
Hello 90
Hello 91
Hello 92
Hello 93
Hello 94
Hello 95
Hello 96
Hello 97
Hello 98
Hello 99
Hello 100
Hello 101
Hello 102
Hello 103
Hello 104
Hello 105
Hello 106
Hello 107
Hello 108
Hello 109
Hello 110
Hel

RecursionError: maximum recursion depth exceeded while calling a Python object

41 -  Factorial using Recurrsion

In [ ]:
def fact(n):
  if n==0:
    return 1

  return n * fact(n-1)

result = fact(5)

print(result)

120


42 - Anonymous Functions | Lambda

In [ ]:
f = lambda a : a*a

result = f(5)

print(result)

25


In [ ]:
f = lambda a,b : a+b

result = f(5,6)

print(result)

11


43 - Filter Map Reduce

In [ ]:
nums = [3,2,6,4,8,2,6,9]

evens = list(filter(lambda n: n%2==0, nums))

doubles = list(map(lambda n: n*2, evens))

# print(evens)
print(doubles)

[4, 12, 8, 16, 4, 12]


In [ ]:
from functools import reduce

# def add_all(a,b):
#   return a+b

nums = [3,2,6,4,8,2,6,9]

evens = list(filter(lambda n: n%2==0, nums))

doubles = list(map(lambda n: n*2, evens))

# sum = reduce(add_all,doubles)

sum = reduce(lambda a,b : a+b,doubles)

print(evens)
print(doubles)
print(sum)

[2, 6, 4, 8, 2, 6]
[4, 12, 8, 16, 4, 12]
56


44 - Decorators

In [ ]:
def div(a,b):
  print(a/b)

def smart_div(func):

  def inner(a,b):
    if a<b:
      a,b = b,a
    return func(a,b)

  return inner

div = smart_div(div)

div(2,4)

2.0


45 - Modules

In [ ]:
def add(a,b):
  return a+b

def sub(a,b):
  return a-b

def multi(a,b):
  return a*b

def div(a,b):
  return a/b

# Basic calculator functions: add, subtract, multiply, divide
# Save this file as calc.py

In [ ]:
# This script imports and uses functions from calc.py
# to perform basic arithmetic operations


from calc import *

a = 9
b = 7

c = add(a,b)
d = sub(a,b)
e = multi(a,b)
f = div(a,b)

print(c)
print(d)
print(e)
print(f)

46 - Special Variable `__name__`

In [ ]:
print (__name__)

__main__


In [ ]:
# Demo.py

print("Hello" + __name__)

In [ ]:
 # Calc.py

 import Calc

 print("Demo Says : " + __name__)

In [ ]:
# Demo.py

def main():

  print("Hello")
  print("Welcome User")

if __name__ == "__main__":
  main()

In [ ]:
 # Calc.py

import Calc

print("Its Time to Calculate")

47 - Special Variable `__name__ `part 2

In [ ]:
# Demo.py
from Calc.py import add

def fun1():
  add()
  print("From fun1")

def fun2():
  print("From fun2")

def main():
  fun1()
  fun2()

main()

In [ ]:
# Calc.py

def add():
  print("Result 1 is ")

def sub():
  print("Result 2 is ")

def main():
  print("in Calc main")
  add()
  sub()

if __name__ == "__main__":
  main()

48 - Object Oriented Programming | Introduction

49 - Classes and Object

In [ ]:
class Computer:

  def config(self):
    print("i5, 16gb, 1TB")

com1 = Computer()
com2 = Computer()

print(type(com1))

Computer.config(com1)
com2.config()

<class '__main__.Computer'>
i5, 16gb, 1TB
i5, 16gb, 1TB


50 - `__init__` menthod

In [ ]:
class Computer:

  def __init__(self, cpu, ram):
    self.cpu = cpu
    self.ram = ram

  def config(self):
    print("Config is ", self.cpu, self.ram)

com1 = Computer('i5',16)
com2 = Computer('Ryzen 3',8)

Computer.config(com1)
com2.config()

Config is  i5 16
Config is  Ryzen 3 8


51 - Constructor, Self and Comparing Objects

In [ ]:
class Computer:

  def __init__(self):
    self.name = "Mukul"
    self.age = 25

  def update(self):
    self.age = 30

c1 = Computer()
c2 = Computer()

c1.name = "Naveen"
c1.age = 16

c1.update()

print(c1.name)
print(c2.name)

Naveen
Mukul


In [ ]:
class Computer:

  def __init__(self):
    self.name = "Mukul"
    self.age = 25

  def update(self):
    self.age = 30

  def compare(self, other):
    if self.age == other.age:
      return True
    else:
      return False

c1 = Computer()
c1.age = 30
c2 = Computer()

if c1.compare(c2):
  print("They are same")
else:
  print("They are different")

c1.update()

print(c1.name)
print(c2.name)

They are different
Mukul
Mukul


52 - Types of Variables

In [ ]:
class Car:

  wheels = 4

  def __init__(self):
    self.mil = 10
    self.com = "BMW"

c1 = Car()
c2 = Car()

c1.mil = 8

Car.wheels = 5

print(c1.com, c1.mil, c1.wheels)
print(c2.com, c2.mil, c2.wheels)

BMW 8 5
BMW 10 5


53 - Types of Methods

In [ ]:
class Student:
  school = "Telusko"

  def __init__(self, m1, m2, m3):
    self.m1 = m1
    self.m2 = m2
    self.m3 = m3

  def avg(self):
    return (self.m1 + self.m2 + self.m3)/3

  def get_m1(self):
    return self.m1

  def set_m1(self, value):
    self.m1 = value

s1 = Student(34,67,32)
s2 = Student(69,32,12)

print(s1.avg())
print(s2.avg())



44.333333333333336
37.666666666666664


In [ ]:
class Student:
  school = "Telusko"

  def __init__(self, m1, m2, m3):
    self.m1 = m1
    self.m2 = m2
    self.m3 = m3

  def avg(self):
    return (self.m1 + self.m2 + self.m3)/3

  @classmethod
  def info(cls):
    return cls.school

s1 = Student(34,67,32)
s2 = Student(69,32,12)

print(s1.avg())
print(s2.avg())
print(Student.info())

44.333333333333336
37.666666666666664
Telusko


In [ ]:
class Student:
  school = "Telusko"

  def __init__(self, m1, m2, m3):
    self.m1 = m1
    self.m2 = m2
    self.m3 = m3

  def avg(self):
    return (self.m1 + self.m2 + self.m3)/3

  @classmethod
  def getSchool(cls):
    return cls.school

  @staticmethod
  def info():
    print("This is an static method")

s1 = Student(34,67,32)
s2 = Student(69,32,12)

print(s1.avg())
print(s2.avg())

Student.info()
print(Student.getSchool())

44.333333333333336
37.666666666666664
This is an static method
Telusko


54 - Inner class

In [ ]:
class Student:

  def __init__(self, name, rollno):
    self.name = name
    self.rollno = rollno

s1 = Student("Mukul", 25)

print(s1.name)
print(s1.rollno)

s2 = Student("Naveen", 16)

print(s2.name)
print(s2.rollno)

Mukul
25
Naveen
16


In [ ]:
class Student:

  def __init__(self, name, rollno):
    self.name = name
    self.rollno = rollno

  def show(self):
    print(self.name, self.rollno)

s1 = Student("Mukul", 25)
s2 = Student("Naveen", 16)

s1.show()

Mukul 25


In [ ]:
class Student:

  def __init__(self, name, rollno):
    self.name = name
    self.rollno = rollno
    self.lap = self.Laptop()

  def show(self):
    print(self.name, self.rollno)
    self.lap.show()

  class Laptop:

    def __init__(self):
      self.brand = "HP"
      self.cpu = "i5"
      self.ram = 8

    def show(self):
      print(self.brand, self.cpu, self.ram)


s1 = Student("Mukul", 25)
s2 = Student("Naveen", 16)

s1.show()

# s1.lap.brand

# lap1 = s1.lap
# lap2 = s2.lap

# print(id(lap1))
# print(id(lap2))

Mukul 25
HP i5 8


55 - Inheritance

Single Level Inheritace

In [ ]:
class A:
  def feature1(self):
    print("Feature 1 working")

  def feature2(self):
    print("Feature 2 working")

class B(A):
  def feature3(self):
    print("Feature 3 working")

  def feature4(self):
    print("Feature 4 working")

a1 = A()

a1.feature1()
a1.feature2()

b1 = B()

b1.feature1()
b1.feature2()
b1.feature3()
b1.feature4()

Feature 1 working
Feature 2 working
Feature 1 working
Feature 2 working
Feature 3 working
Feature 4 working


Multi Level Inheritace

In [ ]:
class A:
  def feature1(self):
    print("Feature 1 working")

  def feature2(self):
    print("Feature 2 working")

class B(A):
  def feature3(self):
    print("Feature 3 working")

  def feature4(self):
    print("Feature 4 working")

class C(B):
  def feature5(self):
    print("Feature 5 working")

a1 = A()

# a1.feature1()
# a1.feature2()

b1 = B()

# b1.feature1()
# b1.feature2()
# b1.feature3()
# b1.feature4()

c1 = C()

c1.feature1()
c1.feature2()
c1.feature3()
c1.feature4()
c1.feature5()

Feature 1 working
Feature 2 working
Feature 3 working
Feature 4 working
Feature 5 working


Multiple Level Inheritace

In [ ]:
class A:
  def feature1(self):
    print("Feature 1 working")

  def feature2(self):
    print("Feature 2 working")

class B:
  def feature3(self):
    print("Feature 3 working")

  def feature4(self):
    print("Feature 4 working")

class C(A,B):
  def feature5(self):
    print("Feature 5 working")

a1 = A()

b1 = B()
# b1.feature3()
# b1.feature4()

c1 = C()
c1.feature1()
c1.feature2()
c1.feature3()
c1.feature4()
c1.feature5()


Feature 1 working
Feature 2 working
Feature 3 working
Feature 4 working
Feature 5 working


56 - Constructor in Inheritance

In [ ]:
class A:

  def __init__(self):
    print("In A init")

  def feature1(self):
    print("Feature 1 working")

  def feature2(self):
    print("Feature 2 working")

class B(A):

  def __init__(self):
    super().__init__()
    print("In B init")

  def feature3(self):
    print("Feature 3 working")

  def feature4(self):
    print("Feature 4 working")

a1 = B()


In A init
In B init


In [ ]:
class A:

  def __init__(self):
    print("In A init")

  def feature1(self):
    print("Feature 1-A working")

  def feature2(self):
    print("Feature 2 working")

class B:

  def __init__(self):
    print("In B init")

  def feature3(self):
    print("Feature 3-B working")

  def feature4(self):
    print("Feature 4 working")

class C(A, B):

  def __init__(self):
    super().__init__()
    print("In C init")

  def feat(self):
    super().feature2()

a1 = C()
a1.feature1()
a1.feat()

In A init
In C init
Feature 1-A working
Feature 2 working


57 - Polymorphism

58 - Duck Typing

In [ ]:
class PyCharm:

  def execute(self):
    print("Compiling")
    print("Running")

class Lapotp:

  def code(self, ide):
    ide.execute()

ide = PyCharm()

lap1 = Lapotp()
lap1.code(ide)


Compiling
Running


In [ ]:
class PyCharm:

  def execute(self):
    print("Compiling")
    print("Running")

class MyEditor:

  def execute(self):
    print("Spell Check")
    print("Convention Check")
    print("Compiling")
    print("Running")

class Lapotp:

  def code(self, ide):
    ide.execute()

ide = MyEditor()

lap1 = Lapotp()
lap1.code(ide)


Spell Check
Convention Check
Compiling
Running


59 - Operator Overloading | Polymorphism

In [ ]:
a = '5'
b = '6'

print(a+b)

print(str.__add__(a,b))


56
56


In [ ]:
class Student:

  def __init__(self, m1, m2):
    self.m1 = m1
    self.m2 = m2

  def __add__(self, other):
    m1 = self.m1 + other.m1
    m2 = self.m2 + other.m2
    s3 = Student(m1, m2)

    return s3

  def __gt__(self, other):
    r1 = self.m1 + self.m2
    r2 = other.m1 + other.m2

    if r1 > r2:
      return True
    else:
      return False

s1 = Student(58,69)
s2 = Student(69,65)

s3 = s1 + s2

print(s3.m1)

if s1 > s2:
  print("s1 wins")
else:
  print("s2 wins")

127
s2 wins


In [ ]:
class Student:

  def __init__(self, m1, m2):
    self.m1 = m1
    self.m2 = m2

  def __add__(self, other):
    m1 = self.m1 + other.m1
    m2 = self.m2 + other.m2
    s3 = Student(m1, m2)

    return s3

  def __gt__(self, other):
    r1 = self.m1 + self.m2
    r2 = other.m1 + other.m2

    if r1 > r2:
      return True
    else:
      return False


  def __str__(self):
    return '{} {}'.format(self.m1, self.m2)

s1 = Student(58,69)
s2 = Student(69,65)

s3 = s1 + s2

print(s3.m1)

if s1 > s2:
  print("s1 wins")
else:
  print("s2 wins")

a = 9
print(a.__str__())

print(s1)
print(s2)

127
s2 wins
9
58 69
69 65


60 - Method Overloading and Method Overriding

In [ ]:
class Student:

  def __init__(self, m1, m2):
    self.m1 = m1
    self.m2 = m2

  def sum(self, a, b):
    s = a + b
    return s

s1 = Student(58,69)

print(s1.sum(5,9))




14


Method Overloading

In [ ]:
class Student:

  def __init__(self, m1, m2):
    self.m1 = m1
    self.m2 = m2

  def sum(self, a=None, b=None, c=None):
    s = 0
    if a != None and b != None and c != None:
      s = a + b + c
    elif a != None and b != None:
      s = a + b
    else:
      s = a
    return s

s1 = Student(58,69)

print(s1.sum(5,9,6))


20


Method Overriding

In [ ]:
class A:

  def show(self):
    print("in A Show")

class B(A):

  def show(self):
    print("in B Show")

a1 = B()
a1.show()

in B Show


Video: Abstract Class and Abstract Method

In [ ]:
from abc import ABC, abstractmethod

class Computer(ABC):
  @abstractmethod
  def process(self):
    pass

class Laptop(Computer):

  def process(self):
    print("It is running")

lap1 = Laptop()
lap1.process()

It is running


In [ ]:
from abc import ABC, abstractmethod

class Computer(ABC):
  @abstractmethod
  def process(self):
    pass

class Laptop(Computer):

  def process(self):
    print("It is running")

class Progammer:
  def work(self):
    print("Solving bugs")

prog1 = Progammer()
prog1.work()

lap1 = Laptop()
lap1.process()


Solving bugs
It is running


In [ ]:
from abc import ABC, abstractmethod

class Computer(ABC):
  @abstractmethod
  def process(self):
    pass

class Laptop(Computer):

  def process(self):
    print("Its running")

class Progammer:
  def work(self, com):
    print("Solving bugs")
    com.process()

comp1 = Laptop()

prog1 = Progammer()
prog1.work(comp1)


Solving bugs
Its running


61 - Iterator

In [ ]:
nums = [7,8,9,5]

it = iter(nums)

print(it.__next__())
print(it.__next__())

7
8


In [ ]:
nums = [7,8,9,5]

it = iter(nums)

print(it.__next__())

print(next(it))

for i in nums:
  print(i)


7
8
7
8
9
5


In [ ]:
class TopTen:

  def __init__(self):
    self.num = 1

  def __iter__(self):
    return self

  def __next__(self):
    if self.num <= 10:
      val = self.num
      self.num += 1
      return val
    else:
      raise StopIteration

values = TopTen()

print(next(values))

for i in values:
  print(i)


1
2
3
4
5
6
7
8
9
10


62 - Generators

In [ ]:
def topten():

  yield 1
  yield 2
  yield 3
  yield 4

values = topten()

# print(values)
print(values.__next__())
print(values.__next__())


1
2


In [ ]:
def topten():

  yield 1
  yield 2
  yield 3
  yield 4

values = topten()

# print(values)
print(values.__next__())

for i in values:
  print(i)


1
2
3
4


In [ ]:
def topten():

  n = 1
  while n <= 10:
    sq = n*n
    yield sq
    n += 1


values = topten()

for i in values:
  print(i)



1
4
9
16
25
36
49
64
81
100


63 - Exception Handling

In [ ]:
a = 5
b = 0

try:
  print(a/b)
except Exception as e:
  print("Hey, you cannot divide a number by zero", e)


Hey, you cannot divide a number by zero division by zero


In [ ]:
a = 5
b = 0

try:
  print("Resource Open")
  print(a/b)

except Exception as e:
  print("Hey, you cannot divide a number by zero", e)
  print("Resource Closed")

Resource Open
Hey, you cannot divide a number by zero division by zero
Resource Closed


In [ ]:
a = 5
b = 2

try:
  print("Resource Open")
  print(a/b)

except Exception as e:
  print("Hey, you cannot divide a number by zero", e)

finally:
  print("Resource Closed")


Resource Open
2.5
Resource Closed


In [ ]:
a = 5
b = 2

try:
  print("Resource Open")
  print(a/b)
  k = int(input("Enter a number: "))
  print(k)

except Exception as e:
  print("Hey, you cannot divide a number by zero", e)

finally:
  print("Resource Closed")

Resource Open
2.5
Enter a number: p
Hey, you cannot divide a number by zero invalid literal for int() with base 10: 'p'
Resource Closed


In [ ]:
a = 5
b = 2

try:
  print("Resource Open")
  print(a/b)
  k = int(input("Enter a number: "))
  print(k)

except ZeroDivisionError as e:
  print("Hey, you cannot divide a number by zero", e)

except ValueError as e:
  print("Invalid Input")

except Exception as e:
  print("Something went wrong...")

finally:
  print("Resource Closed")

Resource Open
2.5
Enter a number: p
Invalid Input
Resource Closed


64 - MultiThreading

In [1]:
class Hello:
  def run (self):
    for i in range(5):
      print("Hello")

class Hi:
  def run (self):
    for i in range(5):
      print("Hi")

t1 = Hello()
t2 = Hi()

t1.run()
t2.run()


Hello
Hello
Hello
Hello
Hello
Hi
Hi
Hi
Hi
Hi


In [6]:
from threading import *

class Hello(Thread):
  def run (self):
    for i in range(10):
      print("Hello")

class Hi(Thread):
  def run (self):
    for i in range(10):
      print("Hi")

t1 = Hello()
t2 = Hi()

# t1.run()
# t2.run()

t1.start()
t2.start()

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi


In [14]:
from threading import *
from time import sleep

class Hello(Thread):
  def run (self):
    for i in range(5):
      print("Hello")
      sleep(1)

class Hi(Thread):
  def run (self):
    for i in range(5):
      print("Hi")
      sleep(1)

t1 = Hello()
t2 = Hi()

# t1.run()
# t2.run()

t1.start()
sleep(0.2)
t2.start()

t1.join()
t2.join()

print ("Bye")

Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi
Bye


65 - File handling

`MyData.txt `

My name is Mukul

Python

Linux

Ayodhya



In [2]:
f = open("MyData.txt", "r")

print(f.read())

My name is Mukul
Python
Linux
Ayodhya


In [3]:
f = open("MyData.txt", "r")

print(f.readline())

My name is Mukul



In [4]:
f = open("MyData.txt", "r")

print(f.readline(), end="")
print(f.readline())

My name is Mukul
Python



create new txt file - abc.txt

In [8]:
f = open("MyData.txt", "r")

f1 = open("abc.txt", "w")

# f1.write("Something")
# f1.write("People")

f1.write('Laptop')

6

In [10]:
f = open("MyData.txt", "r")

f1 = open("abc.txt", "a")

# f1.write('Laptop')

f1.write('Mobile')

6

In [13]:
f = open("MyData.txt", "r")

f1 = open("abc.txt", "w")

for data in f:
  f1.write(data)

In [2]:
f = open("Test.jpg", "rb")

for data in f:
  print(f)

<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<_io.BufferedReader name='Test.jpg'>
<

In [6]:
f = open("Test.jpg", "rb")

f1 = open("MyPic.jpg", "wb")

for data in f:
  f1.write(data)

66 - Comments

In [7]:
# This is a simple program that prints "Hello, World!" on the screen
print("Hello, World!")


Hello, World!


67 - is Python Compiled or Interpreted Language?

68 - Linear Search using Python

In [21]:
pos = -1

def search(list, n):
  i = 0

  while i < len(list):
    if list[i] == n:
      globals()['pos'] = i
      return True
    i = i + 1

  return False

list = [5,4,6,9,8,1]
n = 6

if search(list, n):
  print("Found at", pos+1)
else:
  print("Not Found")


Found at 3


In [22]:
pos = -1

def search(list, n):
  for i in range(len(list)):
    if list[i] == n:
      globals()['pos'] = i
      return True
  return False

list = [5,4,6,9,8,1]
n = 6

if search(list, n):
  print("Found at", pos+1)
else:
  print("Not Found")

Found at 3


69 - Linear Search using Python

In [24]:
pos = -1

def search(list, n):

  l = 0
  u = len(list) - 1

  while l <= u:
    mid = (l + u) // 2

    if list[mid] == n:
      globals()['pos'] = mid
      return True
    else:
      if list[mid] < n:
        l = mid + 1
      else:
        u = mid - 1

  return False

list = [4,7,8,12,45,99]
n = 45

if search(list, n):
  print("Found at", pos+1)
else:
  print("Not Found")


Found at 5


70 - Bubble Sort in python

In [27]:
def sort (nums):
  for i in range(len(nums)-1,0,-1):
    for j in range(i):
      if nums[j] > nums[j+1]:
        temp = nums[j]
        nums[j] = nums[j+1]
        nums[j+1] = temp

nums = [5,9,2,1,67,34,88,34]
sort(nums)
print(nums)


[1, 2, 5, 9, 34, 34, 67, 88]


71 - Selection Sort using Python

In [32]:
def sort (nums):

  for i in range(5):
    minpos = i
    for j in range(i,6):
      if nums[j] < nums[minpos]:
        minpos = j

    temp = nums[i]
    nums[i] = nums[minpos]
    nums[minpos] = temp

    print(nums)

nums = [5,9,2,1,3,7]
sort(nums)
print(nums)


[1, 9, 2, 5, 3, 7]
[1, 2, 9, 5, 3, 7]
[1, 2, 3, 5, 9, 7]
[1, 2, 3, 5, 9, 7]
[1, 2, 3, 5, 7, 9]
[1, 2, 3, 5, 7, 9]


72 - Python Database Connection

73 - Python Database Connection | MySQL

In [34]:
!pip install mysql-connector-python

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.9/33.9 MB 54.1 MB/s eta 0:00:00


In [1]:
import mysql.connector

mydb = mysql.connector.connect(host='localhost', user='root', password='0750')

print(mydb)

In [3]:
import mysql.connector

mydb = mysql.connector.connect(host='localhost', user='root', password='0750')

mycursor = mydb.cursor()

mycursor.execute("show databases")

for x in mycursor:
  print(x)

('information_schema',)
('mukul',)
('mysql',)
('performance_schema',)
('sakila',)
('sys',)
('world',)


Execute SELECT query

In [ ]:
import mysql.connector

mydb = mysql.connector.connect(host='localhost', user='root', password='0750',database='mukul')

mycursor = mydb.cursor()

# SELECT
mycursor.execute("select * from student")

for x in mycursor:
  print(x)

('mukul', 'rmlau')
('shubham', 'rmlau')


In [6]:
import mysql.connector

mydb = mysql.connector.connect(host='localhost', user='root', password='0750',database='mukul')

mycursor = mydb.cursor()

mycursor.execute("select * from student")

result = mycursor.fetchone()

for x in result:
  print(x)

mukul
rmlau


Execute INSERT query

In [31]:
import mysql.connector

mydb = mysql.connector.connect(host='localhost', user='root', password='0750',database='mukul')

mycursor = mydb.cursor()

# SELECT
mycursor.execute("select * from student")
result = mycursor.fetchall()

# INSERT
mycursor.execute("INSERT INTO student (name, college) VALUES ('akshat', 'rmlau')")
mydb.commit()
print("1 row inserted.")

for x in result:
  print(x)

1 row inserted.
('mukul', 'rmlau')
('shubham', 'rmlau')
('akshat', 'rmlau')


Execute DELETE query

In [32]:
import mysql.connector

mydb = mysql.connector.connect(host='localhost', user='root', password='0750', database='mukul')
mycursor = mydb.cursor()

# SELECT
mycursor.execute("SELECT * FROM student WHERE name = 'akshat'")
deleted_data = mycursor.fetchall()

# DELETE the row
mycursor.execute("DELETE FROM student WHERE name = 'akshat'")
mydb.commit()

# Print deleted row(s)
print("---- Deleted Row(s) ----")
for row in deleted_data:
    print(row)


---- Deleted Row(s) ----
('akshat', 'rmlau')
('akshat', 'rmlau')


Execute ALTER query - add a new column 'age'

In [18]:

import mysql.connector

mydb = mysql.connector.connect(host='localhost', user='root', password='0750',database='mukul')

mycursor = mydb.cursor()


# ALTER (add a new column 'age')
try:
    mycursor.execute("ALTER TABLE student ADD COLUMN age INT")
    print("Column 'age' added.")
except:
    print("Column might already exist, skipping.")

mycursor.execute("SELECT * FROM student")
    
columns = [desc[0] for desc in mycursor.description]
print("---- COLUMNS ----")
print(columns)


Column 'age' added.
---- COLUMNS ----
['name', 'college', 'age']


74 - Git | PyCharm | GitHub

75 - Python GitHub Code Contribution